preload = ~/Pictures/wallpaper-0.png
preload = ~/Pictures/wallpaper-1.png
preload = ~/Pictures/wallpaper-2.png
preload = ~/Pictures/wallpaper-3.png
preload = ~/Pictures/wallpaper-4.png
preload = ~/Pictures/wallpaper-5.png
preload = ~/Pictures/wallpaper-6.png
preload = ~/Pictures/wallpaper-7.png
preload = ~/Pictures/wallpaper.jpg

splash = false
ipc = on

wallpaper = DP-2,~/Pictures/wallpaper-1.png
wallpaper = HDMI-A-1,~/Pictures/wallpaper.jpg

# wallpaper {
#   monitor = DP-2
#   path = ~/Pictures/wallpaper-0.png
#   fit-mode = cover
# }
#
# wallpaper {
#   monitor = HDMI-A-1
#   path = ~/Pictures/wallpaper-1.png
#   fit-mode = cover
# }
